In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso, LassoCV
from sklearn.linear_model import ElasticNet, ElasticNetCV
from sklearn.linear_model import Ridge, RidgeCV
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.svm import SVC
from catboost import CatBoostRegressor, Pool
from ngboost import NGBRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor


from sklearn.metrics import mean_squared_error, mean_squared_log_error, mean_absolute_error

from sklearn.model_selection import cross_val_score, KFold, GridSearchCV

import warnings
warnings.filterwarnings(action='ignore')

#-------------------- 차트 관련 속성 (한글처리, 그리드) -----------
#plt.rc('font', family='NanumGothicOTF') # For MacOS
plt.rcParams['font.family']= 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False
sns.set()

#-------------------- 주피터 , 출력결과 넓이 늘리기 ---------------
from IPython.core.display import display, HTML
display(HTML("<style>.container{width:100% !important;}</style>"))
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('max_colwidth', None)

from sklearn.datasets import load_boston

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |████████████████████████████████| 76.1 MB 1.2 MB/s
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.7)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.0.1)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [ ]:
!pip install ngboost

Collecting ngboost
  Downloading ngboost-0.3.12-py3-none-any.whl (31 kB)
Requirement already satisfied: scipy>=1.3 in /usr/local/lib/python3.7/dist-packages (from ngboost) (1.4.1)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.7/dist-packages (from ngboost) (4.62.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from ngboost) (1.19.5)
Collecting lifelines>=0.25
  Downloading lifelines-0.26.4-py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 7.8 MB/s
Requirement already satisfied: scikit-learn>=0.21 in /usr/local/lib/python3.7/dist-packages (from ngboost) (1.0.2)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from lifelines>=0.25->ngboost) (1.3.5)
Requirement already satisfied: autograd>=1.3 in /usr/local/lib/python3.7/dist-packages (from lifelines>=0.25->ngboost) (1.3)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.7/dist-packages (from lifelines>=0.25->ngboost) (3.2.2)
Collecting formulaic<0.3,>=0.2.2
  Downloading formulaic-0.2.4-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 5.6 MB/s
Collecting autograd-gamma>=0.3
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.7/dist-packages (from autograd>=1.3->lifelines>=0.25->ngboost) (0.16.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/dist-packages (from formulaic<0.3,>=0.2.2->lifelines>=0.25->ngboost) (1.13.3)
Requirement already satisfied: astor in /usr/local/lib/python3.7/dist-packages (from formulaic<0.3,>=0.2.2->lifelines>=0.25->ngboost) (0.8.1)
Collecting interface-meta>=1.2
  Downloading interface_meta-1.2.4-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost) (3.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->lifelines>=0.25->ngboost) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0->lifelines>=0.25->ngboost) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21->ngboost) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21->ngboost) (1.1.0)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4048 sha256=190f0b525cd585f9f2e7f73c4a0ae355f526ebc402b0823b47ae379efbf8714c
  Stored in directory: /root/.cache/pip/wheels/9f/01/ee/1331593abb5725ff7d8c1333aee93a50a1c29d6ddda9665c9f
Successfully built autograd-gamma
Installing collected packages: interface-meta, formulaic, autograd-gamma, lifelines, ngboost
Successfully installed autograd-gamma-0.5.0 formulaic-0.2.4 interface-meta-1.2.4 lifelines-0.26.4 ngboost-0.3.12

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
def NMAE(true, pred):
    mae = np.mean(np.abs(true-pred))
    score = mae / np.mean(np.abs(true))
    return score

In [ ]:
import pandas as pd
train = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/comp/housing/dataset/train.csv")
test  = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/comp/housing/dataset/test.csv")

In [ ]:
#커스텀 스코어링
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import make_scorer

In [ ]:
preddf=preddf['id']

NameError: ignored

In [ ]:
preddf

0          1
1          2
2          3
3          4
4          5
        ...
1345    1346
1346    1347
1347    1348
1348    1349
1349    1350
Name: id, Length: 1350, dtype: int64

In [ ]:
CatBoostRegressor(depth = 6, random_state = 10, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.01, verbose = 0)

In [ ]:
def my_fit_score(df):
    y = df["target"]
    X = df.drop(["target"], axis=1)
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, shuffle=True, random_state=1234)
    model_list = [LinearRegression(),Lasso(),ElasticNet(),Ridge(),
                  XGBRegressor(colsample_bytree= 1.0, max_depth= 3, min_child_weight= 1.0, n_estimators= 100),
                  LGBMRegressor(colsample_bytree= 0.8, learning_rate= 0.05, max_depth= 8, n_estimators= 100, subsample= 0.8),
                  RandomForestRegressor(random_state=42,min_samples_leaf= 1, min_samples_split= 6,criterion = 'mae'),
                  CatBoostRegressor(depth = 6, random_state = 10, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.01, verbose = 0),
                  GradientBoostingRegressor(random_state = 42, max_depth = 4, learning_rate = 0.01, n_estimators = 1000),
                  NGBRegressor(random_state = 42, n_estimators = 1000, verbose = 0, learning_rate = 0.03),]
    for model in model_list:
        global preddf
        nmaescore=cross_val_score(model,X_train,y_train,scoring=make_scorer(NMAE,greater_is_better=False),cv=5)
        print(model.__class__.__name__,':',np.mean(nmaescore),)
        model.fit(X_train, y_train)
        preddf[model.__class__.__name__] = model.predict(testfortest)

## 수치화

In [ ]:
train

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target
0,10,2392,5,3,968,5,2392,5,2,2003,2003,2003,386250
1,7,1352,4,2,466,4,1352,5,2,2006,2007,2006,194000
2,5,900,3,1,288,3,864,3,1,1967,1967,1967,123000
3,5,1174,3,2,576,4,680,3,1,1900,2006,2000,135000
4,7,1958,4,3,936,4,1026,4,2,2005,2005,2005,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,6,1756,4,2,422,3,872,5,2,1996,1997,1996,204000
1346,9,2748,4,3,850,5,1850,5,2,2006,2006,2006,390000
1347,5,1214,3,1,318,3,1214,3,2,1967,1967,1967,143000
1348,5,894,3,2,440,3,864,4,1,1974,1974,1974,131000
1349,5,907,3,1,343,3,907,4,1,1978,1978,1978,140000

In [ ]:
train

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target
0,10,2392,5,3,968,5,2392,2392,5,2,2003,2003,2003,386250
1,7,1352,4,2,466,4,1352,1352,5,2,2006,2007,2006,194000
2,5,900,3,1,288,3,864,900,3,1,1967,1967,1967,123000
3,5,1174,3,2,576,4,680,680,3,1,1900,2006,2000,135000
4,7,1958,4,3,936,4,1026,1026,4,2,2005,2005,2005,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,6,1756,4,2,422,3,872,888,5,2,1996,1997,1996,204000
1346,9,2748,4,3,850,5,1850,1850,5,2,2006,2006,2006,390000
1347,5,1214,3,1,318,3,1214,1214,3,2,1967,1967,1967,143000
1348,5,894,3,2,440,3,864,894,4,1,1974,1974,1974,131000
1349,5,907,3,1,343,3,907,907,4,1,1978,1978,1978,140000

In [ ]:
train.replace(['Ex'],5,inplace=True)
train.replace(['Gd'],4,inplace=True)
train.replace(['TA'],3,inplace=True)
train.replace(['Fa'],2,inplace=True)
train.replace(['Po'],1,inplace=True)
train=train.drop('id',axis=1)

In [ ]:
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,4,2,702,5,1800,1800,5,2,2007,2007,2007
1,6,1082,3,1,240,3,1082,1082,3,1,1948,1950,1948
2,6,1573,4,2,440,4,756,769,4,2,2000,2000,2000
3,6,2443,4,3,744,4,1158,1158,4,2,2004,2004,2004
4,5,1040,3,2,686,3,1040,1040,3,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,5,3,774,5,1932,1932,5,2,2008,2008,2008
1346,5,912,3,1,288,3,912,912,3,1,1964,1964,1964
1347,4,861,3,2,288,3,861,861,2,1,1920,1950,1920
1348,5,1430,3,2,624,4,1430,1430,5,2,2004,2005,2004
1349,5,2337,3,2,560,3,662,1422,3,2,1900,1950,1945

In [ ]:
testfortest=test.copy()

In [ ]:
testfortest

,id,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,1,9,1800,Gd,2,702,Ex,1800,1800,Ex,2,2007,2007,2007
1,2,6,1082,TA,1,240,TA,1082,1082,TA,1,1948,1950,1948
2,3,6,1573,Gd,2,440,Gd,756,769,Gd,2,2000,2000,2000
3,4,6,2443,Gd,3,744,Gd,1158,1158,Gd,2,2004,2004,2004
4,5,5,1040,TA,2,686,TA,1040,1040,TA,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,8,1932,Ex,3,774,Ex,1932,1932,Ex,2,2008,2008,2008
1346,1347,5,912,TA,1,288,TA,912,912,TA,1,1964,1964,1964
1347,1348,4,861,TA,2,288,TA,861,861,Fa,1,1920,1950,1920
1348,1349,5,1430,TA,2,624,Gd,1430,1430,Ex,2,2004,2005,2004
1349,1350,5,2337,TA,2,560,TA,662,1422,TA,2,1900,1950,1945

In [ ]:
testfortest=test.drop(['id'],axis=1)
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,Gd,2,702,Ex,1800,1800,Ex,2,2007,2007,2007
1,6,1082,TA,1,240,TA,1082,1082,TA,1,1948,1950,1948
2,6,1573,Gd,2,440,Gd,756,769,Gd,2,2000,2000,2000
3,6,2443,Gd,3,744,Gd,1158,1158,Gd,2,2004,2004,2004
4,5,1040,TA,2,686,TA,1040,1040,TA,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,Ex,3,774,Ex,1932,1932,Ex,2,2008,2008,2008
1346,5,912,TA,1,288,TA,912,912,TA,1,1964,1964,1964
1347,4,861,TA,2,288,TA,861,861,Fa,1,1920,1950,1920
1348,5,1430,TA,2,624,Gd,1430,1430,Ex,2,2004,2005,2004
1349,5,2337,TA,2,560,TA,662,1422,TA,2,1900,1950,1945

In [ ]:

testfortest.replace(['Ex'],5,inplace=True)
testfortest.replace(['Gd'],4,inplace=True)
testfortest.replace(['TA'],3,inplace=True)
testfortest.replace(['Fa'],2,inplace=True)
testfortest.replace(['Po'],1,inplace=True)

In [ ]:
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,4,2,702,5,1800,1800,5,2,2007,2007,2007
1,6,1082,3,1,240,3,1082,1082,3,1,1948,1950,1948
2,6,1573,4,2,440,4,756,769,4,2,2000,2000,2000
3,6,2443,4,3,744,4,1158,1158,4,2,2004,2004,2004
4,5,1040,3,2,686,3,1040,1040,3,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,5,3,774,5,1932,1932,5,2,2008,2008,2008
1346,5,912,3,1,288,3,912,912,3,1,1964,1964,1964
1347,4,861,3,2,288,3,861,861,2,1,1920,1950,1920
1348,5,1430,3,2,624,4,1430,1430,5,2,2004,2005,2004
1349,5,2337,3,2,560,3,662,1422,3,2,1900,1950,1945

In [ ]:
sns.scatterplot(data=train, x="Year Built", y="Garage Yr Blt")

# 이상치 제거

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target,dup
0,10,2392,5,3,968,5,2392,2392,5,2,2003,2003,2003,386250,False
1,7,1352,4,2,466,4,1352,1352,5,2,2006,2007,2006,194000,False
2,5,900,3,1,288,3,864,900,3,1,1967,1967,1967,123000,False
3,5,1174,3,2,576,4,680,680,3,1,1900,2006,2000,135000,False
4,7,1958,4,3,936,4,1026,1026,4,2,2005,2005,2005,250000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,6,1756,4,2,422,3,872,888,5,2,1996,1997,1996,204000,False
1346,9,2748,4,3,850,5,1850,1850,5,2,2006,2006,2006,390000,False
1347,5,1214,3,1,318,3,1214,1214,3,2,1967,1967,1967,143000,False
1348,5,894,3,2,440,3,864,894,4,1,1974,1974,1974,131000,False
1349,5,907,3,1,343,3,907,907,4,1,1978,1978,1978,140000,False

In [ ]:
def outlier_iqr(data, column): 

    # lower, upper 글로벌 변수 선언하기     
    global lower, upper    
    
    # 4분위수 기준 지정하기     
    q25, q75 = np.quantile(data[column], 0.25), np.quantile(data[column], 0.75)          
    
    # IQR 계산하기     
    iqr = q75 - q25    
    
    # outlier cutoff 계산하기     
    cut_off = iqr * 1.5          
    
    # lower와 upper bound 값 구하기     
    lower, upper = q25 - cut_off, q75 + cut_off     
    
    print('IQR은',iqr, '이다.')     
    print('lower bound 값은', lower, '이다.')     
    print('upper bound 값은', upper, '이다.')    
    
    # 1사 분위와 4사 분위에 속해있는 데이터 각각 저장하기     
    data1 = data[data[column] > upper]     
    data2 = data[data[column] < lower]    
    
    # 이상치 총 개수 구하기
    return print('총 이상치 개수는', data1.shape[0] + data2.shape[0], '이다.')

In [ ]:
train[train['Garage Yr Blt'] >= 2200]

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target
254,8,1564,4,2,502,5,1546,1564,4,2,2006,2007,2207,267300

In [ ]:
collist=['Garage Yr Blt']

In [ ]:
for col in collist:
    print('#####',col,'######')
    outlier_iqr(train,col)
    train = train[(train[col] < upper) & (train[col] > lower)]

##### Garage Yr Blt ######
IQR은 41.0 이다.
lower bound 값은 1899.5 이다.
upper bound 값은 2063.5 이다.
총 이상치 개수는 1 이다.

# 스태킹

In [ ]:
from sklearn.ensemble import StackingRegressor

In [ ]:
clf1 =LGBMRegressor(colsample_bytree= 0.8, learning_rate= 0.05, max_depth= 8, n_estimators= 100, subsample= 0.8)
clf2 =RandomForestRegressor(random_state=42,min_samples_leaf= 1, min_samples_split= 6,criterion = 'mae')
clf3 =CatBoostRegressor(depth = 4, random_state = 42, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.03, verbose = 0)
clf4 =GradientBoostingRegressor(random_state = 42, max_depth = 4, learning_rate = 0.01, n_estimators = 1000)

In [ ]:
stack_models = [
    ('lgb', clf1),
    ('rf', clf2),
    ('eln', clf3),
    ('gbr', clf4)
]

In [ ]:
def my_stacking_score(df):
    y = df["target"]
    X = df.drop(["target"], axis=1)
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, shuffle=True, random_state=1234)
    model_list = [StackingRegressor(estimators=stack_models, final_estimator=clf4, n_jobs=-1)]
    for model in model_list:
        global preddf
        nmaescore=cross_val_score(model,X_train,y_train,scoring=make_scorer(NMAE,greater_is_better=False),cv=5)
        print(model.__class__.__name__,':',np.mean(nmaescore),)
        model.fit(X_train, y_train)
        pred=model.predict(testfortest)
        submission = pd.DataFrame({"id" :test['id'],"target": pred})
        submission.to_csv('stacking3.csv', index=False)
        
        #preddf[model.__class__.__name__] = model.predict(test)

In [ ]:
LGBMRegressor : -0.09430876766948046
CatBoostRegressor : -0.09159220007253896
GradientBoostingRegressor : -0.094167066381558
NGBRegressor : -0.0948563751420099

In [ ]:
my_stacking_score(train)

StackingRegressor : -0.0954784767014483

In [ ]:
XGBRegressor : -0.0993685704972019
LGBMRegressor : -0.09430876766948046
RandomForestRegressor : -0.09658731361871134
CatBoostRegressor : -0.09159220007253896
GradientBoostingRegressor : -0.094167066381558
NGBRegressor : -0.0948563751420099

In [ ]:
my_fit_score(train)

LinearRegression : -0.11650341334255702
Lasso : -0.11650170726794107
ElasticNet : -0.11740371074025509
Ridge : -0.11646926437689686
XGBRegressor : -0.10347608832773325
LGBMRegressor : -0.10003901215207667
RandomForestRegressor : -0.10084495542921798
CatBoostRegressor : -0.09588557791920671
GradientBoostingRegressor : -0.10029070364514245
NGBRegressor : -0.1011113486864891

In [ ]:
my_fit_score(train)

LinearRegression : -0.11650341334255696
Lasso : -0.1165017072679411
ElasticNet : -0.1174037107402551
Ridge : -0.11646926437689686
[05:59:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:59:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:59:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:59:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:59:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
XGBRegressor : -0.09999074724680972
[05:59:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
LGBMRegressor : -0.09989267538347243
RandomForestRegressor : -0.10084495542921797
CatBoostRegressor : -0.09430295958363812
GradientBoostingRegressor : -0.10029070364514243
NGBRegressor : -0.10102496943144815

In [ ]:
my_fit_score(train)

LinearRegression : -0.11493212612266931
Lasso : -0.114930729790323
ElasticNet : -0.11615690454908664
Ridge : -0.11490465781527252
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
XGBRegressor : -0.099429942174453
[05:54:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
LGBMRegressor : -0.09890898985829566
RandomForestRegressor : -0.1005564459342766
CatBoostRegressor : -0.0954585315239577
GradientBoostingRegressor : -0.09732650669242507
NGBRegressor : -0.09899792601013456

# 출력하기

In [ ]:
train.drop('dup',axis=1,inplace=True)

In [ ]:
train['dup']=train.duplicated(['Overall Qual', 'Gr Liv Area', 'Exter Qual', 'Garage Cars',
       'Garage Area', 'Kitchen Qual', 'Total Bsmt SF', '1st Flr SF',
       'Bsmt Qual', 'Full Bath', 'Year Built', 'Year Remod/Add',
       'Garage Yr Blt','target'], keep =  False)

In [ ]:
train=train.drop_duplicates(['Overall Qual', 'Gr Liv Area', 'Exter Qual', 'Garage Cars',
       'Garage Area', 'Kitchen Qual', 'Total Bsmt SF', '1st Flr SF',
       'Bsmt Qual', 'Full Bath', 'Year Built', 'Year Remod/Add',
       'Garage Yr Blt','target'], keep =  False)

In [ ]:
train.loc[385,'target']

71000

In [ ]:
train.loc[835,'target']=int((94900+91000)/2)
train=train.drop(1245,axis=0)
train.loc[385,'target']=int(train.loc[385,'target']+train.loc[1175,'target']/2)
train=train.drop(385,axis=0)
train.loc[68,'target']=int(train.loc[68,'target']+train.loc[108,'target']/2)
train=train.drop(108,axis=0)

In [ ]:
train.loc[374,'target']=int(train.loc[374,'target']+train.loc[457,'target']/2)
train=train.drop(457,axis=0)
train.loc[749,'target']=int(train.loc[749,'target']+train.loc[768,'target']/2)
train=train.drop(768,axis=0)
train.loc[711,'target']=int(train.loc[374,'target']+train.loc[457,'target']/2)
train=train.drop(457,axis=0)

In [ ]:
train[train['dup']==True].sort_values(by=['Overall Qual','Gr Liv Area','Year Built'], ascending=True)

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target,dup
735,7,2787,3,4,820,3,1168,1168,5,4,2000,2000,2000,269500,True
939,7,2787,3,4,820,3,1168,1168,5,4,2000,2000,2000,269500,True

In [ ]:
train

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target
0,10,2392,5,3,968,5,2392,2392,5,2,2003,2003,2003,386250
1,7,1352,4,2,466,4,1352,1352,5,2,2006,2007,2006,194000
2,5,900,3,1,288,3,864,900,3,1,1967,1967,1967,123000
3,5,1174,3,2,576,4,680,680,3,1,1900,2006,2000,135000
4,7,1958,4,3,936,4,1026,1026,4,2,2005,2005,2005,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,6,1756,4,2,422,3,872,888,5,2,1996,1997,1996,204000
1346,9,2748,4,3,850,5,1850,1850,5,2,2006,2006,2006,390000
1347,5,1214,3,1,318,3,1214,1214,3,2,1967,1967,1967,143000
1348,5,894,3,2,440,3,864,894,4,1,1974,1974,1974,131000
1349,5,907,3,1,343,3,907,907,4,1,1978,1978,1978,140000

In [ ]:
train=train.drop_duplicates(['Overall Qual', 'Gr Liv Area', 'Exter Qual', 'Garage Cars',
       'Garage Area', 'Kitchen Qual', 'Total Bsmt SF', '1st Flr SF',
       'Bsmt Qual', 'Full Bath', 'Year Built', 'Year Remod/Add',
       'Garage Yr Blt','target'], keep =  'first')

In [ ]:
preddf=pd.DataFrame(data=test['id'],columns=['id'])
preddf

        id
0        1
1        2
2        3
3        4
4        5
...    ...
1345  1346
1346  1347
1347  1348
1348  1349
1349  1350

[1350 rows x 1 columns]

In [ ]:
preddf.head()

,id,LinearRegression,Lasso,ElasticNet,Ridge,XGBRegressor,LGBMRegressor,RandomForestRegressor,CatBoostRegressor,GradientBoostingRegressor,NGBRegressor
0,1,324434.932889,324425.886538,307779.441756,324359.891535,320892.687500,325074.319238,325308.800,320025.511940,328456.067458,326188.673761
1,2,130745.635208,130743.745119,122735.810640,130721.558393,130566.382812,123872.814500,131562.625,128689.116890,129871.847233,132409.300517
2,3,181928.480392,181928.625293,184917.145291,181947.539415,173417.468750,174405.006017,179203.235,176807.126238,175083.159364,171280.109021
3,4,267274.049685,267276.491734,277254.309695,267284.856611,232480.640625,245158.506686,234283.610,252108.756819,236900.608325,246854.400614
4,5,128282.524652,128282.920249,133453.057753,128294.243677,132958.703125,133323.324599,127347.250,132456.050098,133870.962173,133878.768756

In [ ]:
XGBRegressor : -0.0993685704972019
LGBMRegressor : -0.09430876766948046
RandomForestRegressor : -0.09658731361871134
CatBoostRegressor : -0.09159220007253896
GradientBoostingRegressor : -0.094167066381558
NGBRegressor : -0.0948563751420099

In [ ]:
preddf['target']=(preddf['LGBMRegressor']*0.30)+(preddf['NGBRegressor']*0.1)+(preddf['CatBoostRegressor']*0.60)

In [ ]:
preddf

,id,LinearRegression,Lasso,ElasticNet,Ridge,XGBRegressor,LGBMRegressor,RandomForestRegressor,CatBoostRegressor,GradientBoostingRegressor,NGBRegressor,target
0,1,324730.552148,324733.877171,310289.207700,324680.848327,317021.281250,318313.153596,321201.275,322985.799398,328037.287590,321300.982352,321415.523953
1,2,129987.694757,129987.144952,122447.695738,129969.945905,131683.796875,127532.058069,132423.450,129422.003217,132649.028299,131430.016222,129055.820973
2,3,183230.210222,183227.187561,185101.166305,183236.647059,173580.656250,175599.351750,178520.690,178661.576562,173695.136296,170208.041306,176897.555593
3,4,269066.624609,269061.432020,277874.591797,269062.542791,242878.093750,245227.812206,229233.000,254145.509546,240799.102791,242570.457346,250312.695124
4,5,126412.468051,126415.422061,132154.934643,126429.728652,133412.687500,131619.693406,126955.750,133595.904905,133850.356869,130730.239833,132716.474948
...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,336980.516430,336969.776885,323784.831281,336906.635141,350198.906250,342162.870858,327755.865,355832.598221,335041.836116,347826.437118,350931.063902
1346,1347,101551.315222,101552.958210,102387.701587,101557.360793,127604.101562,127659.908114,129593.000,125883.215542,127983.146571,126684.442400,126496.346000
1347,1348,64333.710191,64324.193816,68107.330671,64358.094277,75203.203125,74901.707695,90182.710,76498.998273,69033.688262,61499.120395,74519.823312
1348,1349,206458.493680,206463.428641,212884.924018,206448.481644,195849.937500,202204.806056,212683.420,195712.918930,193569.219831,203865.129229,198475.706098
1349,1350,165691.987537,165692.069712,167631.197415,165712.235985,130729.804688,124322.536471,139892.875,140038.229138,128787.937172,123367.749175,133656.473342

In [ ]:
last=preddf.drop(['Lasso','LinearRegression','ElasticNet','Ridge','XGBRegressor','LGBMRegressor','RandomForestRegressor','CatBoostRegressor'],axis=1)

In [ ]:
df2=preddf[['id','target']]

In [ ]:
df2

        id         target
0        1  321415.523953
1        2  129055.820973
2        3  176897.555593
3        4  250312.695124
4        5  132716.474948
...    ...            ...
1345  1346  350931.063902
1346  1347  126496.346000
1347  1348   74519.823312
1348  1349  198475.706098
1349  1350  133656.473342

[1350 rows x 2 columns]

In [ ]:
df2.to_csv("/content/gdrive/My Drive/Colab Notebooks/comp/housing/dataset/sub11111.csv",index=False)

In [ ]:
b

# 튜닝

In [ ]:
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, GridSearchCV

In [ ]:
params = {'iterations': [500],
          'depth': [4, 5, 6],
          'loss_function': ['Logloss', 'CrossEntropy'],
          'l2_leaf_reg': np.logspace(-20, -19, 3),
          'leaf_estimation_iterations': [10],
#           'eval_metric': ['Accuracy'],
#           'use_best_model': ['True'],
          'logging_level':['Silent'],
          'random_seed': [42]
         }
scorer = make_scorer(accuracy_score)
clf_grid = GridSearchCV(estimator=clf, param_grid=params, scoring=scorer, cv=5)

In [ ]:
CatBoostRegressor(depth = 6, random_state = 10, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.01, verbose = 0)

In [ ]:
y = train['target']
X = train.drop(['target'], axis=1)
X_train,X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.2,
                                                   random_state=1234,
                                                   shuffle=True
                                                      )

model = CatBoostRegressor()
#-- 튜닝 : 하이퍼파라미터 값을 임의로 변경해서 모델의 성능을 좋게 한다.
myparam = {'n_estimators': [500,1000,2000,3000],
          'depth': [4, 5, 6],
          'random_state': [10,20,30,40,42],
          'learning_rate': [0.01,0.02,0.03],
          'verbose': [0],
           'loss_function':['MAE']
         }

skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234) 
gcv_model = GridSearchCV(model, param_grid=myparam, scoring=make_scorer(NMAE,greater_is_better=False), refit=True, cv=5)


gcv_model.fit(X_train, y_train)
print(gcv_model.best_score_)
print(gcv_model.best_params_)
# print(gcv_model.cv_results_)

-0.0954585315239577
{'depth': 6, 'learning_rate': 0.01, 'loss_function': 'MAE', 'n_estimators': 3000, 'random_state': 10, 'verbose': 0}

In [ ]:
y = train['target']
X = train.drop(['target'], axis=1)
X_train,X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.2,
                                                   random_state=1234,
                                                   shuffle=True
                                                      )

model = RandomForestRegressor()
#-- 튜닝 : 하이퍼파라미터 값을 임의로 변경해서 모델의 성능을 좋게 한다.
myparam = {'n_estimators':[10],
           'min_samples_leaf' : [1,2,3,4,5,6,8, 12, 18],
           'min_samples_split' : [1,2,3,4,5,6,8, 16, 20],
           'criterion' : ['mae']
           'objective' : reg:squarederror'
        }

skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234) 
gcv_model = GridSearchCV(model, param_grid=myparam, scoring=make_scorer(NMAE,greater_is_better=False), refit=True, cv=5)


gcv_model.fit(X_train, y_train)
print(gcv_model.best_score_)
print(gcv_model.best_params_)
# print(gcv_model.cv_results_)

SyntaxError: ignored

In [ ]:
y = train['target']
X = train.drop(['target'], axis=1)
X_train,X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.2,
                                                   random_state=1234,
                                                   shuffle=True
                                                      )

model = XGBRegressor(n_estimators=100, random_state=1234)
#-- 튜닝 : 하이퍼파라미터 값을 임의로 변경해서 모델의 성능을 좋게 한다.
myparam = {"colsample_bytree":[1.0],
           "min_child_weight":[1.0,1.2],
           'max_depth': [3,4,6,7,8,9,10],
           'n_estimators': [100,200]
        }

skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234) 
gcv_model = GridSearchCV(model, param_grid=myparam, scoring=make_scorer(NMAE,greater_is_better=False), refit=True, cv=5)


gcv_model.fit(X_train, y_train)
print(gcv_model.best_score_)
print(gcv_model.best_params_)
# print(gcv_model.cv_results_)

-0.10123496542762667
{'colsample_bytree': 1.0, 'max_depth': 3, 'min_child_weight': 1.0, 'n_estimators': 100}

In [ ]:
param_grid = {
    'n_estimators': [100, 200], 
    'learning_rate': [0.1, 0.05, 0.01], 
    'max_depth': [7, 8], 
    'colsample_bytree': [0.8, 0.9], 
    'subsample': [0.8, 0.9,]
}

In [ ]:
y = train['target']
X = train.drop(['target'], axis=1)
X_train,X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.2,
                                                   random_state=1234,
                                                   shuffle=True
                                                      )

model = LGBMRegressor()
#-- 튜닝 : 하이퍼파라미터 값을 임의로 변경해서 모델의 성능을 좋게 한다.
myparam = {
    'n_estimators': [100, 200], 
    'learning_rate': [0.1, 0.05, 0.01], 
    'max_depth': [7, 8], 
    'colsample_bytree': [0.8, 0.9], 
    'subsample': [0.8, 0.9,]
}

skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234) 
gcv_model = GridSearchCV(model, param_grid=myparam, scoring=make_scorer(NMAE,greater_is_better=False), refit=True, cv=5)


gcv_model.fit(X_train, y_train)
print(gcv_model.best_score_)
print(gcv_model.best_params_)
# print(gcv_model.cv_results_)

-0.09936184626042667
{'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'n_estimators': 100, 'subsample': 0.8}

In [ ]:
y = train['target']
X = train.drop(['target'], axis=1)
X_train,X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.2,
                                                   random_state=1234,
                                                   shuffle=True
                                                      )

model = GradientBoostingRegressor()
#-- 튜닝 : 하이퍼파라미터 값을 임의로 변경해서 모델의 성능을 좋게 한다.
myparam = {
    'n_estimators': [1000], 
    'learning_rate': [0.1, 0.05, 0.01], 
    'max_depth': [3,4,5,6,7, 8]
}

skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234) 
gcv_model = GridSearchCV(model, param_grid=myparam, scoring=make_scorer(NMAE,greater_is_better=False), refit=True, cv=5)


gcv_model.fit(X_train, y_train)
print(gcv_model.best_score_)
print(gcv_model.best_params_)

-0.09725219871399923
{'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 1000}

In [ ]:
    model_list = [LinearRegression(),Lasso(),ElasticNet(),Ridge(),
                  XGBRegressor(colsample_bytree= 1.0, max_depth= 3, min_child_weight= 1.0, n_estimators= 100),
                  LGBMRegressor(colsample_bytree= 0.8, learning_rate= 0.05, max_depth= 8, n_estimators= 100, subsample= 0.8),
                  RandomForestRegressor(random_state=42,min_samples_leaf= 1, min_samples_split= 6,criterion = 'mae'),
                  CatBoostRegressor(depth = 4, random_state = 42, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.03, verbose = 0),
                  GradientBoostingRegressor(random_state = 42, max_depth = 4, learning_rate = 0.01, n_estimators = 1000),
                  NGBRegressor(random_state = 42, n_estimators = 1000, verbose = 0, learning_rate = 0.03)]

In [ ]:
LinearRegression : -0.11493212612266945
Lasso : -0.11493072979032301
ElasticNet : -0.11615690454908663
Ridge : -0.11490465781527251
XGBRegressor : -0.10123496542762667
LGBMRegressor : -0.09936184626042667
RandomForestRegressor : -0.1005564459342766
CatBoostRegressor : -0.09711608716605265
GradientBoostingRegressor : -0.09732650669242504
NGBRegressor : -0.09917207417657536

In [ ]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error

In [ ]:
def get_stacking_base_datasets(model,X_train_n,y_train_n,X_test_n,n_folds):
    kf=KFold(n_splits=n_folds,shuffle=False,random_state=0)
    train_fold_pred=np.zeros((X_train_n.shape[0],1))
    test_pred=np.zeros((X_test_n.shape[0],n_folds))
    print(model.__class__.__name__,'model 시작')
    
    for folder_counter,(train_index, valid_index) in enumerate(kf.split(X_train_n)):
        print('\t 폴드 세트:',folder_counter,'시작')
        X_tr=X_train_n[train_index]
        y_tr=y_train_n[train_index]
        X_te=X_train_n[valid_index]
        
        model.fit(X_tr,y_tr)

In [ ]:
y_train

0       386250
1       194000
2       123000
3       135000
4       250000
         ...
1345    204000
1346    390000
1347    143000
1348    131000
1349    140000
Name: target, Length: 1350, dtype: int64

In [ ]:
testfortest=test.copy()

In [ ]:
y = train["target"]
X = train.drop(["target"], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, shuffle=True, random_state=1234)

In [ ]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error

def get_stacking_base_datasets(model, X_train_n,y_train_n,X_test_n,n_folds):
    kf=KFold(n_splits=n_folds, shuffle=True, random_state=1234)
    train_fold_pred=np.zeros((X_train_n.shape[0],1))
    test_pred=np.zeros((X_test_n.shape[0],n_folds))
    print(model.__class__.__name__,'model 시작')
    for folder_counter, (train_index, valid_index) in enumerate(kf.split(X_train_n)):
        print('\t 폴드 세트: ', folder_counter, '시작')
        X_tr=X_train_n[train_index]
        y_tr=y_train_n[train_index]
        X_te=X_train_n[valid_index]
        model.fit(X_tr,y_tr)
        train_fold_pred[valid_index,:]=model.predict(X_te).reshape(-1,1)
        test_pred[:,folder_counter]=model.predict(X_test_n)
    test_pred_mean=np.mean(test_pred,axis=1).reshape(-1,1)
    return train_fold_pred, test_pred_mean

In [ ]:
lgb=LGBMRegressor(colsample_bytree= 0.8, learning_rate= 0.05, max_depth= 8, n_estimators= 100, subsample= 0.8)
cbr=CatBoostRegressor(depth = 4, random_state = 42, loss_function = 'MAE', n_estimators = 3000, learning_rate = 0.03, verbose = 0)
gbr=GradientBoostingRegressor(random_state = 42, max_depth = 4, learning_rate = 0.01, n_estimators = 1000)
ngb=NGBRegressor(random_state = 42, n_estimators = 1000, verbose = 0, learning_rate = 0.03)

In [ ]:
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,Gd,2,702,Ex,1800,1800,Ex,2,2007,2007,2007
1,6,1082,TA,1,240,TA,1082,1082,TA,1,1948,1950,1948
2,6,1573,Gd,2,440,Gd,756,769,Gd,2,2000,2000,2000
3,6,2443,Gd,3,744,Gd,1158,1158,Gd,2,2004,2004,2004
4,5,1040,TA,2,686,TA,1040,1040,TA,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,Ex,3,774,Ex,1932,1932,Ex,2,2008,2008,2008
1346,5,912,TA,1,288,TA,912,912,TA,1,1964,1964,1964
1347,4,861,TA,2,288,TA,861,861,Fa,1,1920,1950,1920
1348,5,1430,TA,2,624,Gd,1430,1430,Ex,2,2004,2005,2004
1349,5,2337,TA,2,560,TA,662,1422,TA,2,1900,1950,1945

In [ ]:
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,Gd,2,702,Ex,1800,1800,Ex,2,2007,2007,2007
1,6,1082,TA,1,240,TA,1082,1082,TA,1,1948,1950,1948
2,6,1573,Gd,2,440,Gd,756,769,Gd,2,2000,2000,2000
3,6,2443,Gd,3,744,Gd,1158,1158,Gd,2,2004,2004,2004
4,5,1040,TA,2,686,TA,1040,1040,TA,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,Ex,3,774,Ex,1932,1932,Ex,2,2008,2008,2008
1346,5,912,TA,1,288,TA,912,912,TA,1,1964,1964,1964
1347,4,861,TA,2,288,TA,861,861,Fa,1,1920,1950,1920
1348,5,1430,TA,2,624,Gd,1430,1430,Ex,2,2004,2005,2004
1349,5,2337,TA,2,560,TA,662,1422,TA,2,1900,1950,1945

In [ ]:
test=pd.read_csv('dataset/test.csv')
testfortest=test.copy()

In [ ]:
testfortest.replace(['Ex'],5,inplace=True)
testfortest.replace(['Gd'],4,inplace=True)
testfortest.replace(['TA'],3,inplace=True)
testfortest.replace(['Fa'],2,inplace=True)
testfortest.replace(['Po'],1,inplace=True)
testfortest=testfortest.drop('id',axis=1)

In [ ]:
testfortest

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt
0,9,1800,4,2,702,5,1800,1800,5,2,2007,2007,2007
1,6,1082,3,1,240,3,1082,1082,3,1,1948,1950,1948
2,6,1573,4,2,440,4,756,769,4,2,2000,2000,2000
3,6,2443,4,3,744,4,1158,1158,4,2,2004,2004,2004
4,5,1040,3,2,686,3,1040,1040,3,1,1968,1968,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,8,1932,5,3,774,5,1932,1932,5,2,2008,2008,2008
1346,5,912,3,1,288,3,912,912,3,1,1964,1964,1964
1347,4,861,3,2,288,3,861,861,2,1,1920,1950,1920
1348,5,1430,3,2,624,4,1430,1430,5,2,2004,2005,2004
1349,5,2337,3,2,560,3,662,1422,3,2,1900,1950,1945

In [ ]:
X_train_n = X_train.values
X_test_n = testfortest.values
y_train_n=y_train.values

lgb_train,lgb_test=get_stacking_base_datasets(lgb,X_train_n,y_train_n,X_test_n,5)
cbr_train,cbr_test=get_stacking_base_datasets(cbr,X_train_n,y_train_n,X_test_n,5)
gbr_train,gbr_test=get_stacking_base_datasets(gbr,X_train_n,y_train_n,X_test_n,5)
ngb_train,ngb_test=get_stacking_base_datasets(ngb,X_train_n,y_train_n,X_test_n,5)

LGBMRegressor model 시작
	 폴드 세트:  0 시작
	 폴드 세트:  1 시작
	 폴드 세트:  2 시작
	 폴드 세트:  3 시작
	 폴드 세트:  4 시작
CatBoostRegressor model 시작
	 폴드 세트:  0 시작
	 폴드 세트:  1 시작
	 폴드 세트:  2 시작
	 폴드 세트:  3 시작
	 폴드 세트:  4 시작
GradientBoostingRegressor model 시작
	 폴드 세트:  0 시작
	 폴드 세트:  1 시작
	 폴드 세트:  2 시작
	 폴드 세트:  3 시작
	 폴드 세트:  4 시작
NGBRegressor model 시작
	 폴드 세트:  0 시작
	 폴드 세트:  1 시작
	 폴드 세트:  2 시작
	 폴드 세트:  3 시작
	 폴드 세트:  4 시작

In [ ]:
Stack_final_X_train=np.concatenate((lgb_train,cbr_train,gbr_train,ngb_train),axis=1)
Stack_final_X_test=np.concatenate((lgb_test,cbr_test,gbr_test,ngb_test),axis=1)

meta_model_ngb=XGBRegressor(colsample_bytree= 1.0, max_depth= 3, min_child_weight= 1.0, n_estimators= 100)

meta_model_ngb.fit(Stack_final_X_train,y_train)
final=meta_model_ngb.predict(Stack_final_X_test)
submission = pd.DataFrame({"id" :test['id'],"target": final})
submission.to_csv('stacking_final_xgb.csv', index=False)

In [ ]:
def NMAE(true, pred):
    mae = np.mean(np.abs(true-pred))
    score = mae / np.mean(np.abs(true))
    return score

In [ ]:
df11=train.duplicated()

In [ ]:
train[train.duplicated(['Overall Qual', 'Gr Liv Area', 'Exter Qual', 'Garage Cars',
       'Garage Area', 'Kitchen Qual', 'Total Bsmt SF', '1st Flr SF',
       'Bsmt Qual', 'Full Bath', 'Year Built', 'Year Remod/Add',
       'Garage Yr Blt'])]

,Overall Qual,Gr Liv Area,Exter Qual,Garage Cars,Garage Area,Kitchen Qual,Total Bsmt SF,1st Flr SF,Bsmt Qual,Full Bath,Year Built,Year Remod/Add,Garage Yr Blt,target
108,4,1092,3,1,253,3,546,546,3,1,1972,1972,1972,85500
244,7,1374,4,2,400,4,384,744,4,2,2004,2004,2004,167000
352,8,1646,4,2,525,4,1594,1646,5,2,2004,2005,2004,300000
457,5,1728,3,2,576,3,1728,1728,3,2,1965,1965,1987,142600
619,8,1324,4,2,550,4,1324,1324,4,2,2006,2006,2006,221370
675,6,1224,4,2,528,4,612,612,4,2,2009,2009,2009,173733
734,7,1368,4,2,474,4,1368,1368,4,2,2005,2006,2005,202500
768,6,848,4,2,420,4,848,848,4,1,2003,2003,2003,131500
795,6,848,4,2,420,4,848,848,4,1,2004,2004,2004,144500
819,7,1492,4,2,440,4,738,738,4,2,2006,2006,2006,185101
827,7,1200,4,2,480,4,600,600,4,2,2004,2005,2004,151000
914,7,1358,4,2,484,4,1350,1358,4,2,2007,2008,2008,217300
939,7,2787,3,4,820,3,1168,1168,5,4,2000,2000,2000,269500
965,7,1626,4,2,474,4,764,764,4,2,2003,2004,2003,155000
970,6,848,4,2,420,4,848,848,4,1,2004,2004,2004,155900
994,7,1080,4,2,496,4,530,530,4,2,2003,2003,2003,147110
1008,7,1456,4,2,400,4,728,728,4,2,2007,2007,2007,177594
1016,6,987,3,1,264,3,483,483,3,1,1973,1973,1973,103400
1086,6,1512,4,2,440,4,756,756,4,2,2000,2000,2000,177000
1115,6,848,4,2,420,4,848,848,4,1,2004,2004,2004,149000
1158,6,1229,3,2,462,3,561,561,4,1,1980,1980,1980,124000
1159,8,1226,4,2,484,4,1226,1226,4,1,1978,1978,1978,206000
1175,4,1092,3,1,286,3,546,546,3,1,1970,1970,1970,88000
1228,7,1344,3,4,784,3,1344,1344,4,2,1997,1998,1997,209200
1245,4,988,3,1,297,3,462,526,4,1,1973,1973,1973,91000
1286,6,848,4,2,420,4,848,848,4,1,2004,2004,2004,143000
1297,8,1280,4,2,506,4,1280,1280,4,2,1992,1992,1992,180000

In [ ]:
train.drop('target',axis=1).columns

Index(['Overall Qual', 'Gr Liv Area', 'Exter Qual', 'Garage Cars',
       'Garage Area', 'Kitchen Qual', 'Total Bsmt SF', '1st Flr SF',
       'Bsmt Qual', 'Full Bath', 'Year Built', 'Year Remod/Add',
       'Garage Yr Blt'],
      dtype='object')

In [ ]:
for i,g in enumerate(df11):
    if g==True:
        print(i)

938